<?php

namespace TomatoPHP\FilamentWallet\Filament\Resources;

use TomatoPHP\FilamentWallet\Filament\Resources\TransactionResource\Pages;
use TomatoPHP\FilamentWallet\Filament\Resources\TransactionResource\RelationManagers;
use TomatoPHP\FilamentWallet\Models\Transaction;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class TransactionResource extends Resource
{
    protected static ?string $model = Transaction::class;

    protected static ?string $navigationIcon = 'heroicon-o-banknotes';

    protected static ?int $navigationSort = 3;


    public static function getNavigationGroup(): ?string
    {
        return trans('filament-wallet::messages.group'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return trans('filament-wallet::messages.transactions.title');
    }

    public static function getPluralLabel(): ?string
    {
        return trans('filament-wallet::messages.transactions.title');
    }

    public static function getLabel(): ?string
    {
        return trans('filament-wallet::messages.transactions.single');
    }

    public static function form(Form $form): Form
    {
        return $form;
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('created_at', 'desc')
            ->columns([
                Tables\Columns\TextColumn::make('created_at')
                    ->label(trans('filament-wallet::messages.transactions.columns.created_at'))
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('payable.name')
                    ->label(trans('filament-wallet::messages.transactions.columns.user'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('wallet.name')
                    ->label(trans('filament-wallet::messages.transactions.columns.wallet'))
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('type')
                    ->label(trans('filament-wallet::messages.transactions.columns.type'))
                    ->badge()
                    ->color(fn (Transaction $transaction) => $transaction->type === 'deposit' ? 'success' : 'danger'),
                Tables\Columns\TextColumn::make('amount')
                    ->label(trans('filament-wallet::messages.transactions.columns.amount'))
                    ->formatStateUsing(fn (Transaction $transaction) => (int) $transaction->amount / 100)
                    ->badge()
                    ->color(fn (Transaction $transaction) => $transaction->amount > 0 ? 'success' : 'danger')
                    ->sortable(),
                Tables\Columns\IconColumn::make('confirmed')
                    ->label(trans('filament-wallet::messages.transactions.columns.confirmed'))
                    ->boolean(),
                Tables\Columns\TextColumn::make('uuid')
                    ->label(trans('filament-wallet::messages.transactions.columns.uuid'))
                    ->searchable(),

                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters(filament('filament-wallet')->useAccounts ? [
               Tables\Filters\SelectFilter::make('payable_id')
                   ->label(trans('filament-wallet::messages.transactions.filters.accounts'))
                    ->searchable()
                    ->options(fn () => config('filament-accounts.model')::query()->pluck('name', 'id')->toArray())
            ] : [])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListTransactions::route('/'),
        ];
    }
}
